### PR TITLE
Added the logo

### LINKED ISSUE #102: Logo
Whenever a user visits a website it looks for a  logo.

Take A Break works as a technique to tackle procrastination. 

A logo above Take A Break would look nice  according to me.

image

I've created the logo in multiple backgrounds in order to make it look nice with different backgrounds.

### PR DESCRIPTION
**Pull request by Sakshi-1701**
### 🛠️ Fixes Issue

Fixes #102 

### 👨‍💻 Changes proposed

Added the logo for Take a break website

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
logo1
logo2

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Please reduce the top margin from the "Take A Break" heading and bring the logo closer to the heading.

**Comment by Sakshi-1701** [comment]
Is it fine now?
logo1 2

**Comment by Daksh777** [comment]
Looks good!

**Comment by Sakshi-1701** [comment]
@Daksh777  I've made the required changes.

**Comment by Daksh777** [comment]
The logo shifts to the left when the settings menu is opened, this needs to be fixed:

https://user-images.githubusercontent.com/43648146/164887460-68fe955b-1aad-4662-8c27-d384f5a4e1b9.mp4

**Pull request closed without merging**
