### PR TITLE
After changes

### LINKED ISSUE #8: Alert before closing the site suddenly after completion of time
Hello @Daksh777 ,

My suggestion is as follows:
Suppose any person started the timer and is exploring his entered site with full concentration, no one would pay any heed to the timer running on tab and then it would be too irritating if the site suddenly closes after the completion of entered time. The user experience would be at stake. In this case I would suggest to **drop 2 time alerts at 50% and 90% completion of time.**

Have a look at my suggestion and drop your valuable comments.

Thanking You,
Roushan Das, 
A GSSOC Contributor.

### LINKED ISSUE #10: Exclusion of the Loading time from user-input time
Hello @Daksh777 ,

The starting loading time of 5 seconds is added to the time the user asks. So it should be excluded from that time and the user should get his full time.

Thanks and Regards,
Roushan Das,
A GSSOC Contributor.

### LINKED ISSUE #47: Using Audio Alerts to make it look more Interactive
### Is your feature request related to a problem? Please describe.

I have already added 2 desktop notifications for alerting user at 50% and 90% completion of time. 
But there are 2 challenges in using desktop notification :- 
(i) The user has to allow for receiving notification
(ii) It can only be used in secured sites (eg https://.....)

### Describe the solution you'd like.

A good solution to this can be 2 voice alerts at 50% and 90% completion of time. The audio control will not be visible on homepage . We could add a computer generated voice audio . Audio will be heard by user even if he is in other window. In addition, this would make the project more interactive and those user who did not allow notification, can also be reminded of the time.

### Describe alternatives you've considered.

I couldn't think of any other alternative better than this but I'll let you know if I get any.

### Add any other context or screenshots about the feature request here.

Hello @Daksh777 ,
Hope you would see to the suggestion and provide me with your thoughts on this matter.

Thanking you,
Roushan Das,
A GSSOC Contributor.

### PR DESCRIPTION
**Pull request by roushandas02**
### 🛠️ Fixes Issue

closes #8 
closes #10 
closes #47 

### 👨‍💻 Changes proposed

made changes to the previous drafts

### ✔️ Check List (Check all the applicable boxes) 

- [ ✔️ ] My code follows the code style of this project.
- [ ✔️ ] This PR does not contain plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Screenshot (246)
Screenshot (247)

### 📄 Note to reviewers (optional)
apologies for creating another PR but I'm slightly new to this Open Source Field.

### CODE REVIEW

**Review by Daksh777 — APPROVED** [review]
Absolutely amazing work @roushandas02!

**Comment by Daksh777** [comment]
Hey @roushandas02 
It seems like the notification access request is not being made. Can you please look into it and create a new PR?

**Comment by roushandas02** [comment]
when the user turns on the notification from the dropdown for the first time, the browser shows "the display desktop  notification request" as shown in the screenshot.

(I) if user agrees to that, the permissions are saved and then user can freely turn off or on the notification from dropdown without getting multiple alerts from browser.

(II) if the user disables the request, then the notifications is not shown

Is this request not being made? click on the i button prior to the site link on tab and click reset permission button then reload the page and try again

**Comment by Daksh777** [comment]
Yes, the request is not being made and I've already reset the permissions.
Can you check on your end in the main website?

**Comment by roushandas02** [comment]
Screenshot (250)_LI

Are you talking about this? I opened it from other device also, it showed this when I turned on the notification from the dropdown for the first time.

**Comment by Daksh777** [comment]
Got it @roushandas02 
It was my browser's settings blocking it. Thank you for your amazing work!

**Pull request merged**
