### PR TITLE
added pause and stop button

### PR DESCRIPTION
**Pull request by Anirban-1490**
### 🛠️ Fixes Issue

#35 

### 👨‍💻 Changes proposed

modified main.js , index.html and main.css to add pause and stop button

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

https://user-images.githubusercontent.com/82874704/165171723-2a2abe9c-8cfe-457d-8139-66f5b79d98a0.mp4

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Amazing work!
Two changes are required: 
- Change the colour of the stop button (hover and normal) to that of the time buttons (like the 5-minute button)
- Change the colour of the cancel button (hover and normal) to that of the swal popup's "No, wait!" button
- Put the stop and the cancel button in a grid on mobile devices, like this: 
image

**Comment by Anirban-1490** [comment]
> Amazing work! Two changes are required:
> 
> * Change the colour of the stop button (hover and normal) to that of the time buttons (like the 5-minute button)
> * Change the colour of the cancel button (hover and normal) to that of the swal popup's "No, wait!" button
> * Put the stop and the cancel button in a grid on mobile devices, like this:
>   image

This looks good ?


Capture
Capture2

**Comment by Daksh777** [comment]
Could you perhaps change the color of the stop text to black? Everything else looks good!

**Comment by Anirban-1490** [comment]
> Could you perhaps change the color of the stop text to black? Everything else looks good!

ok doing it

**Comment by Anirban-1490** [comment]
> Could you perhaps change the color of the stop text to black? Everything else looks good!

check it now

**Review by Daksh777 — CHANGES_REQUESTED** [review]
There seems to be a lot of problems with the times:
- when the website is closed manually (early) and when you click the pause/resume button
- resuming does not work, the timer keeps on going even if you resume it

See this video:

https://user-images.githubusercontent.com/43648146/165947815-4729bcee-6eac-4cbf-b7a3-4d81a60faa29.mp4

**Comment by Anirban-1490** [comment]
> There seems to be a lot of problems with the times:
> 
> * when the website is closed manually (early) and when you click the pause/resume button
> * resuming does not work, the timer keeps on going even if you pause it
> 
> See this video:
> 
>  2022-04-29.18-19-02.mp4

ok right now what i did is completely disabled the pause and stop button if there is no tab opened, as the there is no point for it and the timer is paused by default anyway .

look this -----


https://user-images.githubusercontent.com/82874704/165978249-560850cc-3b4a-4fd7-a835-75ecd1207337.mp4

**Comment by Daksh777** [comment]
Looks good, however, the timer doesn't resume on the same time it as it was paused.

**Comment by Anirban-1490** [comment]
> Looks good, however, the timer doesn't resume on the same time it as it was paused.

That because whoever wrote the code for pausing actually was subtracting time from current time. So no way the time will stay at the same value. But that's nothing to do with my issue right?

**Comment by Daksh777** [comment]
I agree but unfortunately, I cannot merge a non-working feature.
I'm thinking of a possible solution, do let me know if you are able to find a solution too.

**Comment by Anirban-1490** [comment]
> I agree but unfortunately, I cannot merge a non-working feature. I'm thinking of a possible solution, do let me know if you are able to find a solution too.

ok so better will be creating a new issue for improving the pausing functionality. I am creating that and assign me that i will be trying to fix it.  in the meanwhile merge this code.  then merge that new issue

**Comment by Daksh777** [comment]
I don't think a separate issue is required for that, and again, I cannot merge a non-working feature for the main website.

**Comment by Anirban-1490** [comment]
> I don't think a separate issue is required for that, and again, I cannot merge a non-working feature for the main website.

ok so i am fixing it in this pull

**Comment by Anirban-1490** [comment]
> I don't think a separate issue is required for that, and again, I cannot merge a non-working feature for the main website.

ok improved it 


https://user-images.githubusercontent.com/82874704/166314040-5f6f8f97-d503-4d5a-a3dd-c77907a65f4b.mp4

**Review by Daksh777 — APPROVED** [review]

**Comment by Daksh777** [comment]
Great work!

**Comment by Anirban-1490** [comment]
> Great work!

FINALLY!!!! OMG

**Pull request merged**
