### PR TITLE
Dark/colorful theme

### PR DESCRIPTION
**Pull request by harshitab07**
### ✔️ Check List (Check all the applicable boxes) 

- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Good work @harshitab07 
A few changes are required:
- Add more colourful blobs than just red (maybe Google's logos' colors?)
- Your code seems to be triggering a horizontal scroll bar, sometimes even 2 horizontal scroll bars when the blobs are at certain positions. That needs to be fixed
image

**Comment by Daksh777** [comment]
Any update @harshitab07?
It's been 1 week

**Comment by harshitab07** [comment]
Screenshot 2022-03-11 001435
Screenshot 2022-03-11 001558
Screenshot 2022-03-11 001536
)

**Comment by Daksh777** [comment]
Can you please fetch the latest changes in your repo?

**Comment by Daksh777** [comment]
Your PR breaks a lot of things in the website @harshitab07, please check it once
Also, please add the toggle for dark/colorful theme in the settings menu.

**Comment by Daksh777** [comment]
Any updates @harshitab07?

**Pull request closed without merging**
