### PR TITLE
added option of a pop-up todolist

### PR DESCRIPTION
**Pull request by Anjali-Kedia**
### 👨‍💻 Changes proposed

-Added a To Do List option in the drop down 
-Once clicked a pop-up to-do-list appears
-We can add as many options, and delete them once work is done
-Clear all tasks option to clear all the tasks at once
-Once the use of the list is done, click on the option in the drop down to remove pop-up

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
image

image

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Some changes are required:
- The toggle should add the todo list on the bottom of the page and show a popup using swal that it has been added to the bottom.
- Please use the todo list codepen I sent because the current todo list's UI is not very good.

**Comment by Daksh777** [comment]
Correct @Anjali-Kedia.
Make sure to use the to-do list codepen I shared with you as a starting point since it already has animations and some functionality.
The 2nd popup will use SweetAlert2 to show that a to-do list has been added to the bottom of the page.

**Comment by Anjali-Kedia** [comment]
Made the changes.

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Few changes are required:
- The settings menu shifts the title to left when it's opened
image
- The swal popup should follow the same color as the other popups
- The todo list should be added at the bottom of the website, not opened in a new window
- Please use the same design as the one in the codepen, the current one doesn't look as clean and as beautiful and harms the minimalism of the website.

**Pull request closed without merging**
