### PR TITLE
Added an about dialog box

### LINKED ISSUE #16: About section in the website
Hii @Daksh777, 
I felt we could give a small detail as we enter the website (it could be something like Welcome and a short description) or  "About" section, what is Take a break and how it works, at the top right corner as a small button. Any improvements and suggestions on which direction we can go ahead are welcomed, and I want to work on this issue.

### PR DESCRIPTION
**Pull request by kusumita29**
### 🛠️ Fixes Issue
Closes #16 

### 👨‍💻 Changes proposed
Added an info icon at the top left corner which on clicking displays the same text which shows up when someone visits the website for the first time.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Screenshot (617)

### CODE REVIEW

**Comment by kusumita29** [comment]
Please check this PR @Daksh777

**Review by Daksh777 — CHANGES_REQUESTED** [review]
A few changes are required:
- The about icon should be this SVG from [here](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Ainfo%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)
- The swal popup should follow the theme of the other popups
- The text in the popup should have "Product Sans" as the font

**Comment by kusumita29** [comment]
> A few changes are required:
> 
> * The about icon should be this SVG from [here](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Ainfo%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)
> * The swal popup should follow the theme of the other popups
> * The text in the popup should have "Product Sans" as the font

I tried a lot but I am unable to make the changes to the pop-up. I replaced the info icon .png to .svg. Do I create a pull request or unassign myself from this issue?

**Comment by Daksh777** [comment]
You need not worry about themeing and colors, you have to use the same code for the info popup as it is here:
https://github.com/Daksh777/TakeABreak/blob/9b58ba1b647507007a00106c6f2ec46314acb3f3/scripts/main.js#L546-L554

All you have to do is replace the the PNG with the SVG I provided.

**Pull request closed without merging**
