### PR TITLE
An API to fetch motivational quotes images

### PR DESCRIPTION
**Pull request by pushpanjali-10**
Used a motivational image API and replaced the motivational text with that in the time's up popup.
image

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Great work. Can you please do the following:
- Remove the quote (") from the bottom of the image
image
- Remove unused variables (like `apiUrl` and `quote`)

**Comment by pushpanjali-10** [comment]
okay

**Comment by Daksh777** [comment]
Could you please fetch new changes in your repo? I'll merge this then.

**Comment by Daksh777** [comment]
Any update @pushpanjali-10?

**Comment by pushpanjali-10** [comment]
I have already created a pull request sir

**Review by Daksh777 — APPROVED** [review]

**Pull request merged**
