### PR TITLE
Empty site link alert added and https prefix issue examined

### PR DESCRIPTION
**Pull request by rajaditya28**
### 👨‍💻 Changes proposed

1. Used swal to give alert for an empty site link and then not add the site to the grid.
2. Examined the http prefix issue and on closer examination found, that URL was not showing http:// because browsers hide the prefix but in reality http:// prefix is working totally fine.
3. **Whitespaces can be detected too and alert is triggered.**

### ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot 2022-03-02 010430
Screenshot 2022-03-02 010449

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Good work @rajaditya28 
I think the swal popup does not look good in this case and also closes the custom website input popup.
Could you please instead put in red text under the link input field: "Incorrect website URL"

**Comment by rajaditya28** [comment]
> Good work @rajaditya28 
> I think the swal popup does not look good in this case and also closes the custom website input popup.
> Could you please instead put in red text under the link input field: "Incorrect website URL"

I am on it !

**Comment by rajaditya28** [comment]
**On clicking Add Site Button**

Screenshot 2022-03-02 141909

**On Trying to add empty site**

Screenshot 2022-03-02 141832

**After Clicking Ok Button, it doesn't close the custom site popup as you mentioned and asks the user for site link again**

Screenshot 2022-03-02 141909

**If that's okay, I will go ahead and commit these changes so they are visible to you.**

**Review by Daksh777 — CHANGES_REQUESTED** [review]
I think you may have misunderstood what I said.
I wanted to show a red text message under the enter website field if the link is incorrect.
image

Please also add a check for if the name field is empty and show a similar error message

**Comment by rajaditya28** [comment]
> I think you may have misunderstood what I said. I wanted to show a red text message under the enter website field if the link is incorrect. image
> 
> Please also add a check for if the name field is empty and show a similar error message

Yes, I just understood that. Sorry for the misunderstanding. I am working on it.

**Comment by rajaditya28** [comment]
All the functions are working good now Sir

adc

Screenshot 2022-03-02 213656

Screenshot 2022-03-02 213832

I have made sure of all the possible edge cases that could come while using the modal and have taken appropriate measures for them. If color/text readability seems low to you too, kindly suggest which shade should I go with to make alert more readable on greyish/black bakground.

If it seems fine to you, kindly merge the PR.
Thank You !

**Comment by Daksh777** [comment]
Amazing work @rajaditya28!
Can you please change the font to "product sans"? I'll merge it after that.

**Comment by rajaditya28** [comment]
> Amazing work @rajaditya28! Can you please change the font to "product sans"? I'll merge it after that.

Sure I will. Thank You Sir !

**Comment by rajaditya28** [comment]
> Amazing work @rajaditya28! Can you please change the font to "product sans"? I'll merge it after that.

Its done Sir !

**Pull request merged**
