### PR TITLE
Solved issue #167. The settings options are now displayed properly

### LINKED ISSUE #167: The setting options are not displaying properly.
### What happened?

- I have noticed that the Setting options are not responsive, due to which they are going out of the page.

Dekstop view:
image

Mobile view:
image

### How can we reproduce this bug?

- I will improve the CSS and make it responsive. 
- I am a GSSOC'22 participant, kindly assign this issue to me. Thank you.

### PR DESCRIPTION
**Pull request by Rishita489**
### 🛠️ Fixes Issue #167 

Closes #167 

### 👨‍💻 Changes proposed

The settings options are now displayed properly .

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

image

### CODE REVIEW

**Comment by Daksh777** [comment]
Please do not increase the width of the menu and please fix the overflow on the right side.

**Comment by Rishita489** [comment]
ok

**Comment by Rishita489** [comment]
You can review the PR and merge it .

**Comment by Daksh777** [comment]
You have made no changes as I requested, did you forget to push the commit?

**Comment by Rishita489** [comment]
Can you check now . I have pushed the commit .

**Comment by Daksh777** [comment]
There is an overflow on the right side which needs to be fixed

**Comment by Rishita489** [comment]
ok
I will make the changes .

**Comment by Rishita489** [comment]
That overflow issue will exist as the list is getting hidden beyond the screen . If I increase or decrease the width of the list , the options will not be visible . I think this one looks fine .

**Comment by Daksh777** [comment]
You can move the list a little to the left side so it doesn't overflow to the left

**Comment by Rishita489** [comment]
Ok

**Comment by Rishita489** [comment]
I have made the changes . It is now not overflowing to the left .

image

**Review by Daksh777 — APPROVED** [review]

**Comment by Rishita489** [comment]
I think you have to assign this PR to me .Only then it will be counted in my PRs .

**Comment by Rishita489** [comment]
@Daksh777

**Comment by Daksh777** [comment]
That is not the case, it will be counted if the GSSOC and Level labels are added.

**Pull request merged**
