### PR TITLE
improved UI for the timer area

### PR DESCRIPTION
**Pull request by Anirban-1490**
### 🛠️ Fixes Issue

#78 

### 👨‍💻 Changes proposed

Improved the Ui for timer area , added a Circular timer

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

https://user-images.githubusercontent.com/82874704/167314223-69d3dc54-887c-408f-92aa-64988cb93400.mp4

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Great work! Can you please make these changes:
- Change the font to "Product Sans"
- Reduce the padding above the "Enter directly" text so the clock looks a little centered
- Merge the timer's CSS with the main CSS (just put a comment of the timer's CSS)

**Comment by Daksh777** [comment]
That looks great but it seems like it doesn't work anymore and throws a "closed out early" message. Can you please check?

**Comment by Anirban-1490** [comment]
> Oh, oops. You're right, I probably merged a PR and didn't properly check it, my mistake there. Please open a new issue and you can work on it, I'll merge this in the meanwhile.

Thank you

**Comment by Anirban-1490** [comment]
> Please open a new issue and I'll assign it to you @Anirban-1490

yeah doing it

**Pull request merged**
