### PR TITLE
Ajoe12 - Motivational quote generated from api

### PR DESCRIPTION
**Pull request by Ajoe12**
I had added the quotes from  https://type.fit/api/quotes api and it is working perfectly fine. 
Imported a google font for font family in main.css.
I had added some js commands to fetch the api in main.js and css commands to modify the text fonts in main.css.

These are the two screenshots of randomly generated quotes from the api:
Screenshot 2022-03-01 161337

Screenshot 2022-03-01 161413

Please give me feedback for any chances of improvement.

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Great work!
Can you please add something like "Here's a quote to keep you motivated:" (should be left-aligned) and then show the quote?

**Comment by Ajoe12** [comment]
Thank u
Ok  I will add it

**Comment by Ajoe12** [comment]
Screenshot 2022-03-01 185529

Is this okk??

**Comment by Ajoe12** [comment]
I had committed the changes plz review it.

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Just a few last changes:
- Change the font family for the "here's a quote..." to "Product Sans"
- Center align the "here's a quote" since right-aligned doesn't look good
- Add some padding below the "here's a quote" so that there is space between both of them

**Review by Daksh777 — APPROVED** [review]
Great work, I'll merge it

**Pull request merged**
