### PR TITLE
Colorful-theme Updated

### PR DESCRIPTION
**Pull request by Akramovic1**
### 🛠️ Fixes Issue

Colorful-Theme is working fine now

### ✔️ Check List (Check all the applicable boxes) 
- [✔️ ] My code follows the code style of this project.
- [✔️ ] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

Screenshot 2022-05-23 043723

### CODE REVIEW

**Comment by Daksh777** [comment]
You commented out the code which adds the theme setting to local storage, I need that to be there.

**Comment by Akramovic1** [comment]
I added the theme setting to local storage. Check it now.

**Comment by Daksh777** [comment]
Enabling the color theme causes issue with the padding here
image

**Comment by connectnitesh** [comment]
@Akramovic1  please share code with me i would like to resolve the issue @Daksh777

**Comment by Akramovic1** [comment]
Fixed check it now

**Review by Daksh777 — APPROVED** [review]

**Pull request merged**
