### PR TITLE
Add check for custom time input #4

### PR DESCRIPTION
**Pull request by Payalsahb20220**
@Daksh777 sir,
This issue is fix now "Add check for custom time input #4"
Please merge my pull request :)

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
@Payalsahb20220 The swal popup is not displayed if any non number type is entered

**Comment by Payalsahb20220** [comment]
@Daksh777 ok i will fixed it.

**Comment by Payalsahb20220** [comment]
@Daksh777 sir ,  "swal.showInputerror()" in custom function not working properly , and i don't get it why this happening. I search many solution related swal function but none work  on it .
so i used alert function to show error.
here is screenshot of error msg using alert.
Screenshot (41)

**Review by Daksh777 — APPROVED** [review]
No worries @Payalsahb20220 
It's because we're using sweet alert 1, I'll create an issue to migrate to sweet alert 2.

**Pull request merged**
