### PR TITLE
Adding logo

### PR DESCRIPTION
**Pull request by Susmita-Dey**
### 👨‍💻 Changes proposed
- Added the logo in the `assets` folder.
- Linked the image in the `index.html` file
- Styled the `div` containing the image in the `IconFont.css` file.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
image

### 📄 Note to reviewers (optional)
I'm a GSSoC'22 contributor. I've made the requested changes. Kindly merge this to the main.

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Please add some top padding on the logo so the text looks centered and please also fix the logo for mobile devices 
image

**Comment by Susmita-Dey** [comment]
@Daksh777 okay

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Susmita-Dey** [comment]
@Daksh777 Okay, I'll do it by tomorrow.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Daksh777** [comment]
Any update @Susmita-Dey?

**Comment by Susmita-Dey** [comment]
> Any update @Susmita-Dey?

I've added the padding at the top. Kindly check if it's okay or not. 
image

**Comment by Susmita-Dey** [comment]
@Daksh777 I've made the changes as requested. Kindly check it and merge it to main.

**Comment by Daksh777** [comment]
Can you please fetch all the changes in your repo?

**Comment by Susmita-Dey** [comment]
> Can you please fetch all the changes in your repo?

You mean fetch upstream?

**Comment by Daksh777** [comment]
Yes @Susmita-Dey

**Comment by Susmita-Dey** [comment]
> Yes @Susmita-Dey

Done

**Review by Daksh777 — APPROVED** [review]

**Pull request merged**
