### PR TITLE
reload confirmation 

### PR DESCRIPTION
**Pull request by vickyrules**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by vickyrules** [comment]
hey @Daksh777  
i tried very hard but not able to delay or stop reload untill user permission from swal or custom meaasages.
read more here:
https://stackoverflow.com/questions/38879742/is-it-possible-to-display-a-custom-message-in-the-beforeunload-popup

so i fix the issue with default pop up message.

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Currently, on every reload, the user is being asked if they want to leave the website. 
However, the pop up should only be made when the user has selected a timer (you can use onclick event listener on the buttons for this)

**Comment by vickyrules** [comment]
> Currently, on every reload, the user is being asked if they want to leave the website. However, the pop up should only be made when the user has selected a timer (you can use onclick event listener on the buttons for this)

@Daksh777 resolved

**Review by Daksh777 — APPROVED** [review]
Smart work @vickyrules, very well done!

**Pull request merged**
