### PR TITLE
An update to Issue #52 

### PR DESCRIPTION
**Pull request by AKD-01**

### CODE REVIEW

**Comment by AKD-01** [comment]
closes #52

**Comment by Daksh777** [comment]
Can you please fetch the latest changes in your repo? Your repo is a bit old.

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Awesome work, just a few changes are required:
- Remove the 'card label' and 'link' title and replace the placeholders with "Name" and "Link" (like it is in the SweetAlert2 documentation)
- Remove the white dividers
- Use the `Swal.showValidationMessage()` for throwing errors if the website URL is invalid (you can implement the regex directly in the if condition) and if there is no name entered in the name input. You can remove the code used for doing that for the old card/popup
- Change the input font to "Product Sans"

**Review by Daksh777 — APPROVED** [review]
Awesome work!

**Comment by AKD-01** [comment]
> Awesome work!

Thank you! ✨

**Pull request merged**
