### PR TITLE
added check for empty url condition ( in Enter Website Directly input field )

### PR DESCRIPTION
**Pull request by masterpranay1**
- Check If User trying to continue leaving the field vacant
- If vacant, then fires an alert ( using SWAL )
- else go to that website url

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
It does not work. I can still enter space or any other character and it still opens.
Please look into using regex to check if the entered URL is correct or not.
Note that all example.com, www.example.com and https://example.com should be treated as correct

**Comment by masterpranay1** [comment]
I have added the validation of url using a regex.

**Review by Daksh777 — APPROVED** [review]
Great work, I'll merge it

**Comment by Daksh777** [comment]
Hey @masterpranay1 
While clicking on the arrow button works, if I enter a URL in the field and press enter button, it still loads an empty page. Can you please fix that?

**Comment by masterpranay1** [comment]
Yes!! I would try to fix this.

**Pull request merged**
