### PR TITLE
Fixed Buttons alignment + Removed Unnecessary codes

### PR DESCRIPTION
**Pull request by Anirban-1490**
### 🛠️ Fixes Issue

#145 

### 👨‍💻 Changes proposed

Fixed alignment and responsiveness of the buttons and alose removed "Huge" chunks of unnecessary codes that was causing
responsive issue

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

https://user-images.githubusercontent.com/82874704/170964975-03a076e6-ff58-419e-bfca-d44fa167065d.mp4

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
Please do not reduce the size of the button and the padding between them

| New  | Old |
| ------------- | ------------- |
|  image |  image |

**Comment by Anirban-1490** [comment]
> Please do not reduce the size of the button and the padding between them
> 
> New	Old
> image	image

ok working

**Comment by Anirban-1490** [comment]
@Daksh777 check now

**Comment by Daksh777** [comment]
The buttons are still the same size (compare them with the buttons on the main website)

**Comment by Anirban-1490** [comment]
> The buttons are still the same size (compare them with the buttons on the main website)

fixed it . check it, this is as close as i can get

**Review by Daksh777 — APPROVED** [review]

**Pull request merged**
