### PR TITLE
abbreviate it

### PR DESCRIPTION
**Pull request by Rishabh-Gaud**
### ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
image
### video 

https://user-images.githubusercontent.com/65586827/158872452-2abca2db-e70c-4c2f-8f29-3e3f7fd6076f.mp4

### CODE REVIEW

**Review by Daksh777 — CHANGES_REQUESTED** [review]
That is not what I meant @Rishabh-Gaud.
I meant that the custom time input field should take time in abbreviations (like 30m, 1h, etc), not the buttons.

**Comment by Rishabh-Gaud** [comment]
@Daksh777  sure sir now I get it.

**Comment by Rishabh-Gaud** [comment]
@Daksh777  Sir, I made the required Changes please review it.

**Review by Daksh777 — APPROVED** [review]

**Comment by Daksh777** [comment]
@Rishabh-Gaud Can you also add the abbreviation for seconds (abbreviated with `s`)?

**Comment by Piyush-Aman** [comment]
> @Rishabh-Gaud Can you also add the abbreviation for seconds (abbreviated with `s`)?

@Daksh777 Sir I saw all the code base and I want to contribute in this repo and I fully aware what you want sir plz give me chance I want to work on this issue.

**Comment by Daksh777** [comment]
Sure @Piyush-Aman

**Comment by Daksh777** [comment]
@Piyush-Aman Any updates?

**Comment by Piyush-Aman** [comment]
Sir give me 1-2 days I will do that .

**Pull request merged**
